#!/bin/bash -x
#SBATCH --job-name=sm_bas_MC
#SBATCH --mail-user=jbruckmann@eonerc.rwth-aachen.de
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=1
#SBATCH --time=00:20:00
#SBATCH --output=out.txt
#SBATCH --error=err.txt

module load LIBRARIES
module load hdf5

export LD_LIBRARY_PATH=/usr/local_rwth/sw/HDF5/1.10.4/gcc_4.8.5-intelmpi_2018.4.274/lib:$LD_LIBRARY_PATH

 srun -n 2 shem_sm_sgsim64gnu_bas.x
